
# Nue settings
globals: ["@global", css]
libs: ["@lib", docs/lib, blog/lib]

og: /img/og-blue-big.png
view_transitions: true
native_css_nesting: true
origin: https://nuejs.org
heading_ids: true

# Content settings
title: Web Framework For UX Developers
description: Build the slickest websites in the world and wonder why you ever did them any other way
title_template: "Nue - %s"
favicon: /icon/favicon.png

# preload header hover image
# prefetch: [/icon/present-light.svg]

# Markdown link references
links:
  nuejs: //github.com/nuejs/nue/tree/master/packages/nuejs
  divide: //css-tricks.com/the-great-divide/
  standards: //developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards
  brad: //bradfrost.com/blog/post/front-of-the-front-end-and-back-of-the-front-end-web-development/
  gds: //bradfrost.com/blog/post/a-global-design-system/
  spa: /docs/single-page-applications
  soc: //en.wikipedia.org/wiki/Separation_of_concerns
