
# Nue settings
globals: ["@global", css]
libs: ["@lib", docs/lib, blog/lib]

og: /img/standards-first.png
favicon: /img/favblue.png
view_transitions: true
native_css_nesting: true
origin: https://nuejs.org
heading_ids: true

# Content settings
title: The standards-first web framework
description: Nue is a close-to-metal framework for fast tooling and clean code. It's the modern HTML, Markdown, CSS, and JavaScript taken to their absolute peak
title_template: "%s - Nue"

# Markdown link references
links:
  standards: //developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards
  nuejs: //github.com/nuejs/nue/tree/master/packages/nuejs
  divide: //css-tricks.com/the-great-divide/
  brad: //bradfrost.com/blog/post/front-of-the-front-end-and-back-of-the-front-end-web-development/
  gds: //bradfrost.com/blog/post/a-global-design-system/
  spa: /docs/single-page-applications
  soc: //en.wikipedia.org/wiki/Separation_of_concerns
