
# Nue settings
globals: ["@global", css]
libs: ["@lib", docs/lib, blog/lib]

css_2023: true
view_transitions: true
grid_item_class: card


# Content settings
title: Web Framework For UX Developers
description: Nue is a web framework for UX focused projects. It's the best choice for designers and UX developers.
title_template: "Nue - %s"
favicon: /icon/favicon.png


# Navigation
header:
  Branding:
    - image: /img/logo.svg
      class: logo
      alt: Nue logo
      size: 60 × 18
      url: /

  Site navigation:
    - Docs: /docs/
    - Blog: /blog/
    - label: Nue beta is out ›
      url: /blog/status-update-01/
      class: status badge

  Toolbar:
    - label: Try beta
      url: /docs/
    - ---
    - image: /icon/x-logo.svg
      url: //x.com/tipiirai
      class: social
      alt: X logo
      size: 39 x 39

    - label: 6.0k
      url: //github.com/nuejs/nue
      class: github badge

burger_menu:
  - Home: /home/
  - Docs: /docs/
  - Blog: /blog/
  - ---
  - GitHub: //github.com/nuejs/nue

footer:
  branding:
    - image: /img/logo.svg
      size: 65 × 19
      url: /

  navi:
    Developers:
      - Nue introduction: /docs/
      - Installation: /docs/installation.html
      - Blog: /blog/
      - FAQ: /docs/faq.html
      - GitHub: //github.com/nuejs/nue

    Key Concepts:
      - UX development flow: /docs/ux-development.html
      - Global Design System: /docs/global-design-system.html
      - CSS best practices: /docs/css-best-practises.html
      - Content development: /docs/content.html
      - Single-page apps: /docs/single-page-applications.html


# Markdown link references
links:
  nuejs: //github.com/nuejs/nue/tree/master/packages/nuejs
  divide: //css-tricks.com/the-great-divide/
  standards: //developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards
  brad: //bradfrost.com/blog/post/front-of-the-front-end-and-back-of-the-front-end-web-development/
  gds: //bradfrost.com/blog/post/a-global-design-system/
  spa: /docs/single-page-applications
  soc: //en.wikipedia.org/wiki/Separation_of_concerns