
include: [technical-content, video, switchbox, syntax-highlight]
footer: false

lang:
  menu: Menu
  this_page: On this page

sidenav:
  Getting started:
    - What is Nue?: /docs/
    - Installation: installation.html
    - Hello, World!: hello-world.html
    - Project Structure: project-structure.html
    - Settings and metadata: settings.html
    - Command line interface: command-line-interface.html

  UX development:
    - Global Design System: global-design-system.html
    - UX development: ux-development.html
    - Page layout: page-layout.html
    - Custom layouts: custom-layouts.html
    - Motion and Reactivity: reactivity.md
    - Optimization: performance-optimization.html


  Content development:
    - Content authoring: content.html
    - Built-in tags: tags.html


  Application development:
    - Single-page applications: single-page-applications.html
    - Model development
    - UI development


  Reference:
    - Syntax highlighting
    - Template syntax
    - Content collections
    - Hot-reloading