
include: [technical-content, video, switchbox, syntax-highlight]
footer: false

lang:
  menu: Menu
  this_page: On this page

sidenav:
  Getting started:
    - What is Nue?: /docs/
    - Installation: installation.html
    - Hello, World!: hello-world.html
    - Project Structure: project-structure.html
    - Command line interface: command-line-interface.html

  Design:
    - Global Design System: global-design-system.html
    - Layout system: layout-system.html
    - Styling framework
    - Syntax highlighting
    - label: Optimizations
      url: performance-optimization.html
    - CSS best practices


  Reactivity:
    - Reactivity layer
    - Page transitions
    - Reactive islands
    - JavaScript modules


  Content:
    - Content management
    - Components



  Single-page Apps:
    - SPA fundamentals
    - Application logic
    - Views and routing
    - Headless UI library
    - Look and feel

  Reference:
    - Settings index
    - Template syntax
    - Hot-reloaing