
include: [technical-content, video, switchbox, syntax-highlight]
footer: false

lang:
  menu: Menu
  this_page: On this page

sidenav:
  Getting started:
    - What is Nue?: /docs/
    - Installation: installation.html
    - Hello, World!: hello-world.html
    - Project Structure: project-structure.html
    - Command line interface: command-line-interface.html


  UX development:
    - Global Design System: global-design-system.html
    - UX development flow: ux-development.html
    - Page layout
    - Navigation
    - Motion design
    - Reactivity
    - Optimization: performance-optimization.html


  Content development:
    - Writing rich content
    - Component index


  App development:
    - Single-page applications
    - Models and API design
    - Views and routing

  Reference:
    - Settings
    - UI components
    - Template syntax
