
include: [technical-content, video, switchbox, syntax-highlight]
footer: false

lang:
  menu: Menu
  this_page: On this page

sidenav:
  Getting started:
    - label: Content-first framework
      url: /docs/
    - label: Installation
      url: installation.html
    - label: Hello, World!
      url: hello-world.html
    - label: Files and directories
      url: files-and-directories.html
    - Command line interface

  Design System:
    - Global Design System
    - Layout system
    - Styling framework
    - Syntax highlighting
    - CSS best practices
    - label: Performance optimization
      url: performance-optimization.html


  Reactivity:
    - Reactivity fundamentals
    - In-page reactivity
    - Page transitions
    - Reactive islands


  Content authoring:
    - Content Management System
    - Writing rich content
    - Component index



  Single-page Applications:
    - SPA fundamentals
    - Application logic
    - Views and routing
    - Headless UI library
    - Look and feel

  Reference:
    - Settings index
    - Template syntax
    - Hot-reloaing