
include: [technical-content, video, switchbox, syntax-highlight]
footer: false

lang:
  menu: Menu
  this_page: On this page

sidenav:
  Getting started:
    - What is Nue?: /docs/
    - Installation: installation.html
    - Hello, World!: hello-world.html
    - Project Structure: project-structure.html
    - Command line interface: command-line-interface.html

  UX development:
    - Global Design System: global-design-system.html
    - Theming
    - Motion
    - Interactivity
    - label: Optimization
      url: performance-optimization.html
    - CSS best practices


  Content development:
    - Content design
    - Content management
    - Markdown extensions


  Application development:
    - Single-page applications
    - API design
    - Views and routing
    - UI components


  Reference:
    - Page layouts: page-layouts.html
    - Component layouts: component-layouts.html
    - Template syntax
    - Settings index
    - Hot-reloaing