
include: [technical-content, syntax-highlight, form, video]

authors:
  default: tero

  tero:
    name: Tero Piirainen
    img: /img/tero.webp
    x: tipiirai

  john:
    name: John Doe
    img: /img/john.webp
    x: johndoe